; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC-1 on Sun Aug 23 2020 21:38:04 GMT+0800 (中国标准时间)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


