; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC-1 on Sun Aug 23 2020 21:38:10 GMT+0800 (中国标准时间)
; Wait for set temperatures to be reached
M116 P0

